/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.1.321.0
    Soft IP Version: 1.9.0
    2026 07 08 13:02:43
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module MPCS_ex (use_refmux_i, diffioclksel_i, clksel_i, sdq_refclkp_q0_i,
    sdq_refclkn_q0_i, sdq_refclkp_q1_i, sdq_refclkn_q1_i, sd_ext_0_refclk_i,
    sd_ext_1_refclk_i, pll_0_refclk_i, pll_1_refclk_i, sd_pll_refclk_i,
    acjtag_mode_i, acjtag_enable_i_0, acjtag_acmode_i_0, acjtag_drive1_i_0,
    acjtag_highz_i_0, acjtagpout_o_0, acjtagnout_o_0, lmmi_clk_i_0,
    lmmi_resetn_i_0, lmmi_request_i_0, lmmi_wr_rdn_i_0, lmmi_offset_i_0,
    lmmi_wdata_i_0, lmmi_rdata_valid_o_0, lmmi_ready_o_0, lmmi_rdata_o_0,
    sd0rxp_i, sd0rxn_i, sd0txp_o, sd0txn_o, sd0_rext_i, sd0_refret_i,
    mpcs_rx_usr_clk_i_0, mpcs_tx_usr_clk_i_0, mpcs_tx_pcs_rstn_i_0,
    mpcs_rx_pcs_rstn_i_0, mpcs_rx_out_clk_o_0, mpcs_tx_out_clk_o_0,
    mpcs_perstn_i_0, mpcs_tx_ch_din_i_0, mpcs_tx_fifo_st_o_0,
    mpcs_rx_ch_dout_o_0, mpcs_rx_fifo_st_o_0, mpcs_ebuf_empty_o_0,
    mpcs_ebuf_full_o_0, mpcs_anxmit_i_0, mpcs_walign_en_i_0,
    mpcs_get_lsync_o_0, mpcs_rx_get_lalign_o_0, mpcs_rx_deskew_en_i_0,
    mpcs_clkin_i_0, mpcs_pwrdn_i_0, mpcs_txhiz_i_0, mpcs_rxidle_o_0,
    mpcs_rxerr_i_0, mpcs_fomreq_i_0, mpcs_fomack_o_0, mpcs_fomrslt_o_0,
    mpcs_speed_o_0, mpcs_txval_i_0, mpcs_phyrdy_o_0, mpcs_ready_o_0,
    mpcs_rxoob_i_0, mpcs_txdeemp_i_0, mpcs_pwrst_o_0, mpcs_skipbit_i_0,
    mpcs_rxval_o_0)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  use_refmux_i;
    input  diffioclksel_i;
    input  [1:0]  clksel_i;
    input  sdq_refclkp_q0_i;
    input  sdq_refclkn_q0_i;
    input  sdq_refclkp_q1_i;
    input  sdq_refclkn_q1_i;
    input  sd_ext_0_refclk_i;
    input  sd_ext_1_refclk_i;
    input  pll_0_refclk_i;
    input  pll_1_refclk_i;
    input  sd_pll_refclk_i;
    input  acjtag_mode_i;
    input  acjtag_enable_i_0;
    input  acjtag_acmode_i_0;
    input  acjtag_drive1_i_0;
    input  acjtag_highz_i_0;
    output  acjtagpout_o_0;
    output  acjtagnout_o_0;
    input  lmmi_clk_i_0;
    input  lmmi_resetn_i_0;
    input  lmmi_request_i_0;
    input  lmmi_wr_rdn_i_0;
    input  [8:0]  lmmi_offset_i_0;
    input  [7:0]  lmmi_wdata_i_0;
    output  lmmi_rdata_valid_o_0;
    output  lmmi_ready_o_0;
    output  [7:0]  lmmi_rdata_o_0;
    input  sd0rxp_i;
    input  sd0rxn_i;
    output  sd0txp_o;
    output  sd0txn_o;
    input  sd0_rext_i;
    input  sd0_refret_i;
    input  mpcs_rx_usr_clk_i_0;
    input  mpcs_tx_usr_clk_i_0;
    input  mpcs_tx_pcs_rstn_i_0;
    input  mpcs_rx_pcs_rstn_i_0;
    output  mpcs_rx_out_clk_o_0;
    output  mpcs_tx_out_clk_o_0;
    input  mpcs_perstn_i_0;
    input  [79:0]  mpcs_tx_ch_din_i_0;
    output  [3:0]  mpcs_tx_fifo_st_o_0;
    output  [79:0]  mpcs_rx_ch_dout_o_0;
    output  [3:0]  mpcs_rx_fifo_st_o_0;
    output  mpcs_ebuf_empty_o_0;
    output  mpcs_ebuf_full_o_0;
    input  mpcs_anxmit_i_0;
    input  mpcs_walign_en_i_0;
    output  mpcs_get_lsync_o_0;
    output  mpcs_rx_get_lalign_o_0;
    input  mpcs_rx_deskew_en_i_0;
    input  mpcs_clkin_i_0;
    input  [1:0]  mpcs_pwrdn_i_0;
    input  mpcs_txhiz_i_0;
    output  mpcs_rxidle_o_0;
    input  mpcs_rxerr_i_0;
    input  mpcs_fomreq_i_0;
    output  mpcs_fomack_o_0;
    output  [7:0]  mpcs_fomrslt_o_0;
    output  [1:0]  mpcs_speed_o_0;
    input  mpcs_txval_i_0;
    output  mpcs_phyrdy_o_0;
    output  mpcs_ready_o_0;
    input  mpcs_rxoob_i_0;
    input  mpcs_txdeemp_i_0;
    output  [1:0]  mpcs_pwrst_o_0;
    input  mpcs_skipbit_i_0;
    output  mpcs_rxval_o_0;
endmodule