`timescale 100 ps/100 ps
(* black_box_pad_pin="SDRXP,SDRXN,SDTXP,SDTXN,SDREXT,SDREFRET,SDQ_REFCLKP,SDQ_REFCLKN" *)module PCSX1 (
  PMACLKIN,
  TXCLK,
  RXCLK,
  CCCLK,
  PIPE_PCS_TXCLKOUT,
  RXOUTCLK,
  TX_ALIGN_CLKIN,
  RX_ALIGN_CLKIN,
  TX_ALIGN_CLKOUT,
  RX_ALIGN_CLKOUT,
  PERSTN,
  MPCS_TX_URSTN,
  MPCS_RX_URSTN,
  LMMICLK,
  LMMIRESETN,
  LMMIREQUEST,
  LMMIWR_RDN,
  LMMIOFFSET,
  LMMIWDATA,
  LMMIRDATA_VALID,
  LMMIREADY,
  LMMIRDATA,
  SDRXP,
  SDRXN,
  SDTXP,
  SDTXN,
  SDREXT,
  SDREFRET,
  SDQ_REFCLKP,
  SDQ_REFCLKN,
  AUXCLK,
  PCLKAUX_SEL_LL,
  ALTCLKIN,
  ALTCLK_SEL,
  CLKREQI,
  CLKREQO,
  CLKREQOE,
  TX_LALIGN_IN_UP,
  TX_LALIGN_IN_DOWN,
  TX_LALIGN_OUT_UP,
  TX_LALIGN_OUT_DOWN,
  PIPE_POWER_DOWN,
  PIPE_RATE,
  PIPE_TXDETECTRX,
  PIPE_RX_EQEVAL,
  PIPE_INVALID_REQUEST,
  PIPE_RX_PRESET_HINTEN,
  PIPE_RX_PRESET_HINT,
  PIPE_RX_POL,
  PIPE_TX_CLKREQ,
  PIPE_TXCOMM_DIS,
  PIPE_RXEI_DIS,
  PIPE_L1PMSSEN,
  PIPE_L1X_ENTRY_REQ,
  PIPE_TX_SWING,
  PIPE_TX_MARGIN,
  PIPE_TX_DEEMPH,
  PIPE_TX_DEEMPH_PCS_TX_DATA,
  PIPE_LOCAL_GET_PRESET_COEF,
  PIPE_TX_DATA_VLD,
  PIPE_TX_EI,
  PIPE_TX_DATA_PCS_TX_DATA,
  PIPE_TX_DATAK_PCS_TX_DATA,
  PIPE_TX_COMP_PCS_TX_DATA,
  PIPE_TX_START_BLK_PCS_TX_DATA,
  PIPE_TX_SYNC_HDR_PCS_TX_DATA,
  PIPE_BLKALGNCTRL,
  LINK0_CSR_PIPE_RESET,
  PIPE_WIDTH_5G0,
  PIPE_WIDTH_8G0,
  PIPE_RXEQ_FOM,
  PIPE_PHY_STATUS,
  PIPE_RX_EI,
  PIPE_RX_CLKREQ,
  PIPE_L1X_ENTRY_ACK,
  PIPE_LOCAL_GET_TX_PRESET_COEF,
  PIPE_TX_PRESET_COEF_PCS_RX_DATA,
  PIPE_RX_START_BLOCK,
  PIPE_RX_DATA_PCS_RX_DATA,
  PIPE_RX_STATUS_PCS_RX_DATA,
  PIPE_RX_DATA_EN_PCS_RX_DATA,
  PIPE_RX_VLD_PCS_RX_DATA,
  PIPE_RX_DATA_VLD_PCS_RX_DATA,
  PIPE_RX_SYNC_HDR_PCS_RX_DATA,
  PCIELL_MODESEL,
  PIPE_WIDTH_2G5_LL,
  PIPE_WIDTH_5G0_LL,
  PIPE_WIDTH_8G0_LL,
  PIPE_POWER_DOWN_LL,
  PIPE_RATE_LL,
  PIPE_TX_DETECT_RX_LOOPBACK_LL,
  PIPE_RX_EQ_EVAL_LL,
  PIPE_INVALID_REQUEST_LL,
  PIPE_RX_EQ_EVAL_FEEDBACK_FOM_LL,
  PIPE_RX_EQ_EVAL_FEEDBACK_DIR_LL,
  PIPE_RX_PRESET_HINT_ENABLE_LL,
  PIPE_RX_PRESET_HINT_LL,
  PIPE_PHY_STATUS_LL,
  PIPE_RX_POLARITY_LL,
  PIPE_RX_ELEC_IDLE_LL,
  PIPE_RX_CLKREQ_N_LL,
  PIPE_TX_CLKREQ_N_LL,
  PIPE_TX_CM_DISABLE_LL,
  PIPE_RX_EI_DISABLE_LL,
  PIPE_L1PMSSEN_LL,
  PIPE_TX_SWING_LL,
  PIPE_TX_MARGIN_LL,
  PIPE_TX_DEEMPH_LL,
  PIPE_TX_DEEMPH_WINDOW_LL,
  PIPE_LOCAL_FS_LL,
  PIPE_LOCAL_LF_LL,
  PIPE_LOCAL_GET_PRESET_COEF_LL,
  PIPE_LOCAL_GET_PRESET_INDEX_LL,
  PIPE_LOCAL_GET_TX_COEF_VALID_LL,
  PIPE_LOCAL_GET_TX_PRESET_COEF_LL,
  PIPE_REMOTE_FS_LL,
  PIPE_REMOTE_LF_LL,
  PIPE_REMOTE_EQ_RX_DEEMPH_LL,
  PIPE_REMOTE_EQ_RX_PRESET_LL,
  PIPE_TX_DATA_ENABLE_LL,
  PIPE_TX_DATA_VALID_LL,
  PIPE_TX_START_BLOCK_LL,
  PIPE_TX_SYNC_HEADER_LL,
  PIPE_TX_DATA_LL,
  PIPE_TX_DATAK_LL,
  PIPE_TX_COMPLIANCE_LL,
  PIPE_TX_ELEC_IDLE_LL,
  PIPE_RX_DATAEN_LL,
  PIPE_RX_DATA_VALID_LL,
  PIPE_RX_START_BLOCK_LL,
  PIPE_RX_SYNC_HEADER_LL,
  PIPE_BLOCK_ALIGN_CONTROL_LL,
  PIPE_RX_DATA_LL,
  PIPE_RX_DATAK_LL,
  PIPE_RX_VALID_LL,
  PIPE_RX_STATUS_LL,
  PIPE_PCLKOUT_LL,
  PIPE_PRESET_INDX_PCS_TX_DATA,
  PIPE_REMOTE_FS_PCS_TX_DATA,
  PIPE_REMOTE_LF_PCS_TX_DATA,
  PIPE_RX_DEEMPH_PCS_TX_DATA,
  PIPE_RX_PRESET_PCS_TX_DATA,
  PIPE_WIDTH_2G5,
  PIPE_RXEQ_DIR_PCS_RX_DATA,
  PIPE_RXEQ_DIR_PCS_RX_FIFO_ST,
  PIPE_LOCAL_FS_PCS_RX_DATA,
  PIPE_LOCAL_LF_PCS_RX_DATA,
  PIPE_LOCAL_GET_TX_COEF_VLD,
  PIPE_TX_DATA_EN,
  PIPE_RX_DATAK_PCS_RX_DATA,
  PCS_RX_DATA,
  PCS_RX_HI_BER,
  PCS_RX_BLK_LOCK,
  PCS_TX_FIFO_ST,
  ACTMD,
  ACTEN,
  ACTACMD,
  ACTDR11,
  ACTHIGHZ,
  ACJPOUT,
  ACJNOUT,
  SCAN_CLK,
  SCAN_RST
)
;
input PMACLKIN ;
input TXCLK ;
input RXCLK ;
input CCCLK ;
output PIPE_PCS_TXCLKOUT ;
output RXOUTCLK ;
input TX_ALIGN_CLKIN ;
input RX_ALIGN_CLKIN ;
output TX_ALIGN_CLKOUT ;
output RX_ALIGN_CLKOUT ;
input PERSTN ;
input MPCS_TX_URSTN ;
input MPCS_RX_URSTN ;
input LMMICLK ;
input LMMIRESETN ;
input LMMIREQUEST ;
input LMMIWR_RDN ;
input [8:0] LMMIOFFSET ;
input [7:0] LMMIWDATA ;
output LMMIRDATA_VALID ;
output LMMIREADY ;
output [7:0] LMMIRDATA ;
input SDRXP ;
input SDRXN ;
output SDTXP ;
output SDTXN ;
input SDREXT ;
input SDREFRET ;
input SDQ_REFCLKP ;
input SDQ_REFCLKN ;
input AUXCLK ;
output PCLKAUX_SEL_LL ;
input ALTCLKIN ;
input ALTCLK_SEL ;
input CLKREQI ;
output CLKREQO ;
output CLKREQOE ;
input [7:0] TX_LALIGN_IN_UP ;
input [7:0] TX_LALIGN_IN_DOWN ;
output [7:0] TX_LALIGN_OUT_UP ;
output [7:0] TX_LALIGN_OUT_DOWN ;
input [1:0] PIPE_POWER_DOWN ;
input [1:0] PIPE_RATE ;
input PIPE_TXDETECTRX ;
input PIPE_RX_EQEVAL ;
input PIPE_INVALID_REQUEST ;
input PIPE_RX_PRESET_HINTEN ;
input [2:0] PIPE_RX_PRESET_HINT ;
input PIPE_RX_POL ;
input PIPE_TX_CLKREQ ;
input PIPE_TXCOMM_DIS ;
input PIPE_RXEI_DIS ;
input PIPE_L1PMSSEN ;
input PIPE_L1X_ENTRY_REQ ;
input PIPE_TX_SWING ;
input [2:0] PIPE_TX_MARGIN ;
input [15:0] PIPE_TX_DEEMPH ;
input [1:0] PIPE_TX_DEEMPH_PCS_TX_DATA ;
input PIPE_LOCAL_GET_PRESET_COEF ;
input PIPE_TX_DATA_VLD ;
input PIPE_TX_EI ;
input [31:0] PIPE_TX_DATA_PCS_TX_DATA ;
input [3:0] PIPE_TX_DATAK_PCS_TX_DATA ;
input PIPE_TX_COMP_PCS_TX_DATA ;
input PIPE_TX_START_BLK_PCS_TX_DATA ;
input [1:0] PIPE_TX_SYNC_HDR_PCS_TX_DATA ;
input PIPE_BLKALGNCTRL ;
input LINK0_CSR_PIPE_RESET ;
output [1:0] PIPE_WIDTH_5G0 ;
output [1:0] PIPE_WIDTH_8G0 ;
output [7:0] PIPE_RXEQ_FOM ;
output PIPE_PHY_STATUS ;
output PIPE_RX_EI ;
output PIPE_RX_CLKREQ ;
output PIPE_L1X_ENTRY_ACK ;
output [3:0] PIPE_LOCAL_GET_TX_PRESET_COEF ;
output [13:0] PIPE_TX_PRESET_COEF_PCS_RX_DATA ;
output PIPE_RX_START_BLOCK ;
output [31:0] PIPE_RX_DATA_PCS_RX_DATA ;
output [2:0] PIPE_RX_STATUS_PCS_RX_DATA ;
output PIPE_RX_DATA_EN_PCS_RX_DATA ;
output PIPE_RX_VLD_PCS_RX_DATA ;
output PIPE_RX_DATA_VLD_PCS_RX_DATA ;
output [1:0] PIPE_RX_SYNC_HDR_PCS_RX_DATA ;
input [2:0] PCIELL_MODESEL ;
output [1:0] PIPE_WIDTH_2G5_LL ;
output [1:0] PIPE_WIDTH_5G0_LL ;
output [1:0] PIPE_WIDTH_8G0_LL ;
input [1:0] PIPE_POWER_DOWN_LL ;
input [1:0] PIPE_RATE_LL ;
input PIPE_TX_DETECT_RX_LOOPBACK_LL ;
input PIPE_RX_EQ_EVAL_LL ;
input PIPE_INVALID_REQUEST_LL ;
output [7:0] PIPE_RX_EQ_EVAL_FEEDBACK_FOM_LL ;
output [5:0] PIPE_RX_EQ_EVAL_FEEDBACK_DIR_LL ;
input PIPE_RX_PRESET_HINT_ENABLE_LL ;
input [2:0] PIPE_RX_PRESET_HINT_LL ;
output PIPE_PHY_STATUS_LL ;
input PIPE_RX_POLARITY_LL ;
output PIPE_RX_ELEC_IDLE_LL ;
output PIPE_RX_CLKREQ_N_LL ;
input PIPE_TX_CLKREQ_N_LL ;
input PIPE_TX_CM_DISABLE_LL ;
input PIPE_RX_EI_DISABLE_LL ;
input PIPE_L1PMSSEN_LL ;
input PIPE_TX_SWING_LL ;
input [2:0] PIPE_TX_MARGIN_LL ;
input [17:0] PIPE_TX_DEEMPH_LL ;
input PIPE_TX_DEEMPH_WINDOW_LL ;
output [5:0] PIPE_LOCAL_FS_LL ;
output [5:0] PIPE_LOCAL_LF_LL ;
input PIPE_LOCAL_GET_PRESET_COEF_LL ;
input [3:0] PIPE_LOCAL_GET_PRESET_INDEX_LL ;
output PIPE_LOCAL_GET_TX_COEF_VALID_LL ;
output [17:0] PIPE_LOCAL_GET_TX_PRESET_COEF_LL ;
input [5:0] PIPE_REMOTE_FS_LL ;
input [5:0] PIPE_REMOTE_LF_LL ;
input [17:0] PIPE_REMOTE_EQ_RX_DEEMPH_LL ;
input [3:0] PIPE_REMOTE_EQ_RX_PRESET_LL ;
output PIPE_TX_DATA_ENABLE_LL ;
input PIPE_TX_DATA_VALID_LL ;
input PIPE_TX_START_BLOCK_LL ;
input [1:0] PIPE_TX_SYNC_HEADER_LL ;
input [31:0] PIPE_TX_DATA_LL ;
input [3:0] PIPE_TX_DATAK_LL ;
input PIPE_TX_COMPLIANCE_LL ;
input PIPE_TX_ELEC_IDLE_LL ;
output PIPE_RX_DATAEN_LL ;
output PIPE_RX_DATA_VALID_LL ;
output PIPE_RX_START_BLOCK_LL ;
output [1:0] PIPE_RX_SYNC_HEADER_LL ;
input PIPE_BLOCK_ALIGN_CONTROL_LL ;
output [31:0] PIPE_RX_DATA_LL ;
output [3:0] PIPE_RX_DATAK_LL ;
output PIPE_RX_VALID_LL ;
output [2:0] PIPE_RX_STATUS_LL ;
output PIPE_PCLKOUT_LL ;
input [3:0] PIPE_PRESET_INDX_PCS_TX_DATA ;
input [5:0] PIPE_REMOTE_FS_PCS_TX_DATA ;
input [5:0] PIPE_REMOTE_LF_PCS_TX_DATA ;
input [17:0] PIPE_RX_DEEMPH_PCS_TX_DATA ;
input [3:0] PIPE_RX_PRESET_PCS_TX_DATA ;
output [1:0] PIPE_WIDTH_2G5 ;
output [3:0] PIPE_RXEQ_DIR_PCS_RX_DATA ;
output [1:0] PIPE_RXEQ_DIR_PCS_RX_FIFO_ST ;
output [5:0] PIPE_LOCAL_FS_PCS_RX_DATA ;
output [5:0] PIPE_LOCAL_LF_PCS_RX_DATA ;
output PIPE_LOCAL_GET_TX_COEF_VLD ;
output PIPE_TX_DATA_EN ;
output [3:0] PIPE_RX_DATAK_PCS_RX_DATA ;
output [5:0] PCS_RX_DATA ;
output PCS_RX_HI_BER ;
output PCS_RX_BLK_LOCK ;
output [1:0] PCS_TX_FIFO_ST ;
input ACTMD ;
input ACTEN ;
input ACTACMD ;
input ACTDR11 ;
input ACTHIGHZ ;
output ACJPOUT ;
output ACJNOUT ;
input SCAN_CLK ;
input SCAN_RST ;
endmodule /* PCSX1 */

module PCSREFMUX (
  DIFFIOCLK0,
  DIFFIOCLK1,
  PLLCLK0,
  PLLCLK1,
  CLK,
  CLKOUT,
  DIFFIOCLKSEL,
  CLKSEL
)
;
input DIFFIOCLK0 ;
input DIFFIOCLK1 ;
input PLLCLK0 ;
input PLLCLK1 ;
input CLK ;
output CLKOUT ;
input DIFFIOCLKSEL ;
input [1:0] CLKSEL ;
endmodule /* PCSREFMUX */

