#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/Lattice_MPC_Ex/impl_1}]} {
  file mkdir {C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/Lattice_MPC_Ex/impl_1}
}
cd {C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/Lattice_MPC_Ex/impl_1}

sys_set_attribute -gui on -msg {C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/Lattice_MPC_Ex/promote.xml}
msg_load {C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/Lattice_MPC_Ex/promote.xml}
des_set_project_udb -in {Lattice_MPC_Ex_impl_1_syn.udb} -out {Lattice_MPC_Ex_impl_1_map.udb} -milestone map -pm jd5d00
des_set_reference_udb -clean
map_set_option {pdc_file "C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/constraints/MPCS_ex.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false vio false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
