#-- Lattice Semiconductor Corporation Ltd.
#-- Bitgen run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/Lattice_MPC_Ex/promote.xml}
msg_load {C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/Lattice_MPC_Ex/promote.xml}
des_set_project_udb -in {Lattice_MPC_Ex_impl_1.udb} -milestone bit -pm jd5d00
# bitgen option
bit_set_option { enable_early_io_wakeup false output_format "binary"   ip_evaluation true register_initialization true bitstream_mode normal }
#-- write result file
bit_generate -w {C:/Users/Kumar Lab/Desktop/Jasper/Lattice Projects/MPCS_ex/Lattice_MPC_Ex/impl_1/Lattice_MPC_Ex_impl_1}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
